apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: spring-boot
spec:
  selector:
    app: spring-service-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort